## tic Circle CI template: linux-matrix-deploy
## revision date: 2022-03-01
version: 2.1
jobs:
  r-release:
    # r-release-env
    environment:
    docker:
      - image: cimg/rlang:4.2.0
    steps:
      - checkout

      # create a unique env var for the cache. Unfortunately normal env vars
      # are not picked up by the cache, therefore this workaround is needed.
      # See https://discuss.circleci.com/t/cannot-use-circle-yml-environment-variables-in-cache-keys/10994/7
      # - run: echo "$(date '+%d-%m')-r-release" > /tmp/_tmp_file
      # - restore_cache:
      #     key: R-package-library-{{ checksum "/tmp/_tmp_file" }}

      # install deps and check pkg ---------------------------------------------
      - run:
          name: "[r-release] Install dependencies"
          command: |
            sudo apt update && sudo apt install -y libgit2-dev
            echo -e 'options(Ncpus = 4, repos = structure(c(CRAN = "https://packagemanager.rstudio.com/cran/__linux__/focal/latest")))' > $HOME/.Rprofile
            R -q -e 'install.packages("tidyverse")'
            R -q -e 'install.packages("tic", repos = structure(c(ropensci = "https://ropensci.r-universe.dev", CRAN = "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"))); print(tic::dsl_load()); tic::prepare_all_stages()'
            R -q -e 'tic::before_install()'
            R -q -e 'tic::install()'

      - run:
          name: "[r-release] R CMD Check"
          no_output_timeout: 60m
          command: |
            R -q -e 'tic::before_script()'
            R -q -e 'tic::script()'

      # save R pkg cache -------------------------------------------------------
      # - save_cache:
      #     key: R-package-library-{{ checksum "/tmp/_tmp_file" }}
      #     paths:
      #       - /usr/local/lib/R/site-library

workflows:
  build-and-deploy:
    jobs:
      - r-release

    jobs:
      - r-release
