on:
  push:

name: docker

jobs:
  all:
    runs-on: ubuntu-latest

    name: docker

    steps:
      - uses: actions/checkout@v2

      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: tic
          image_tag: 3.6.3
          dockerfile: Dockerfile
