on:
  push:

name: docker

jobs:
  all:
    runs-on: ubuntu-latest

    name: docker

    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pats22/tic
          tags: latest
          path: .github/docker
