on:
  push:

name: docker

jobs:
  all:
    runs-on: ubuntu-latest

    name: docker

    steps:
      - uses: actions/checkout@v2

      - name: "Prepare build context"
        run: |
          cp DESCRIPTION .github/docker

      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: tic
          image_tag: 3.6.3
          dockerfile: .github/docker/3.6.3.Dockerfile
